#!/usr/bin/perl -w
# Author : Daniel Cox (danielcoxman@gmail.com)
# Date : 12/17/2017
# version 1.0
# Check IS-IS interface status on erk8k, vsp9k

#interface mibs for vsp7k IS-IS
#1.3.6.1.4.1.2272.1.63.2.1
#1.3.6.1.2.1.138.1.3.2
#adjacency mibs for vsp7k IS-IS
#1.3.6.1.4.1.2272.1.63.10.1
#1.3.6.1.2.1.138.1.6.1
# Mibs used
# isisSysAdminState       1.3.6.1.3.37.1.1.1.8.0
# isisCircIfIndex         1.3.6.1.3.37.1.3.2.1.2
# isisCircAdminState      1.3.6.1.3.37.1.3.2.1.3
# isisCircType            1.3.6.1.3.37.1.3.2.1.5
# rcIsisCircuitOperState  1.3.6.1.4.1.2272.1.63.2.1.8
# rcIsisCircuitNumAdj     1.3.6.1.4.1.2272.1.63.2.1.9
# rcIsisCircuitNumUpAdj   1.3.6.1.4.1.2272.1.63.2.1.10
# rcMltId                 1.3.6.1.4.1.2272.1.17.10.1.1
# rcMltName               1.3.6.1.4.1.2272.1.17.10.1.2
# rcMltPortMembers        1.3.6.1.4.1.2272.1.17.10.1.3
# rcMltIfIndex            1.3.6.1.4.1.2272.1.17.10.1.11
# rcIsisLogicalInterfaceIfIndex   1.3.6.1.4.1.2272.1.63.26.1.2
# rcIsisLogicalInterfaceName      1.3.6.1.4.1.2272.1.63.26.1.8
# rcIsisLogicalInterfaceCircIndex 1.3.6.1.4.1.2272.1.63.26.1.10
# rcPortName              1.3.6.1.4.1.2272.1.4.10.1.1.35
# IfIndex                 1.3.6.1.2.1.2.2.1.1
# ifDescr                 1.3.6.1.2.1.2.2.1.2
# IfName                  1.3.6.1.2.1.31.1.1.1.1
# ifAlias                 1.3.6.1.2.1.31.1.1.1.18
# ifAdminStatus           1.3.6.1.2.1.2.2.1.7
# snmpwalk -v 2c -c public 10.2.1.4 1.3.6.1.2.1.2.2.1.1 
# snmpwalk -v 2c -c public 10.2.1.4 1.3.6.1.2.1.2.2.1.2 
# snmpwalk -v 2c -c public 10.2.1.4 1.3.6.1.2.1.31.1.1.1.1 
# snmpwalk -v 2c -c public 10.2.1.4 1.3.6.1.2.1.31.1.1.1.18
use strict;
use warnings;
use Getopt::Std;

# initialize some variables
use vars qw( %options $host $community $verbose);

# setup variable for state of checks and some strings to print 
my $STATE_WARNING = 1;
my $STATE_UNKNOWN = 3;
my $STATE_OK = 0;
my $result;
my $statewarning;
my $rstring = "";
my $estring = "";
my $oid;

# get options -v -H and -C. -H and -C require a value
getopts( 'vH:C:', \%options );

&print_usage() if ( ! $options{ H } );
&print_usage() if ( ! $options{ C } );
$host = $options{ H };
$community = $options{ C };
$verbose = $options{ v };

# print usage if I do not get options I need
sub print_usage {
    print "Usage: $0 -H <ip or hostname> -C community [-v verbose]\n";
    exit $STATE_UNKNOWN;
}

### set string for snmpget and snmpwalk commands with options
my $snmpget  = "snmpget -OenQ -v2c -c $community $host" ;
my $snmpget2  = "snmpget -Oen -v2c -c $community $host" ;
my $snmpwalk = "snmpwalk -OenQ -v2c -c $community $host";

### snmpget to see what kind of switch it is
my $cmd;
if ( $verbose ) { 
    $cmd ="$snmpget .1.3.6.1.2.1.1.1.0 .1.3.6.1.2.1.1.2.0 .1.3.6.1.2.1.1.3.0 .1.3.6.1.2.1.1.5.0";
    my @sysinfo =`$cmd`; if ($?) { print "Error command failed: $cmd\n"; exit $STATE_UNKNOWN; }
    my $sysDescr = &fix_snmp_result($sysinfo[0]);
    my $sysObjectID = &fix_snmp_result($sysinfo[1]);
    my $sysUpTime = &fix_snmp_result($sysinfo[2]);
    my $sysName = &fix_snmp_result($sysinfo[3]);
    print "sysDescr *$sysDescr*\n"; 
    print "sysObjectID *$sysObjectID*\n";
    print "sysUpTime *$sysUpTime*\n";
    print "sysName *$sysName*\n";
}

# check to see if isis globally enabled
my $isisSysAdminState = `$snmpget 1.3.6.1.3.37.1.1.1.8.0`;
# Global hash to store isis interfaces
my %isis;
$isisSysAdminState = &fix_snmp_result($isisSysAdminState);
if ( $isisSysAdminState == 1 ) { 
    &get_isis_interfaces;
    if ( $verbose ) { print "OK: IS-IS globally enabled\n"; }
} else {
    if ( $verbose ) { print "OK: IS-IS NOT globally enabled\n"; }
}


# Global hash to store isis logical interfaces
my %RcIsisLogicalInterfaceEntry;
my @logical_temp = `$snmpwalk 1.3.6.1.4.1.2272.1.63.26.1.2`;
# Check to see if isis logical exist
if ( grep( ! /No Such/, @logical_temp ) ) { 
    if ( $verbose ) { print "OK: isis logical interfaces exist\n"; }
    &get_isis_logical;
} else { 
    if ( $verbose ) { print "OK: NO isis logical interfaces\n"; }
}

# Global hash to store mlt
my %rcMltTable;
my @rcMltTable_temp = `$snmpwalk 1.3.6.1.4.1.2272.1.17.10.1.1`;
# Check to see if MLT exist
if ( grep( ! /No Such/, @rcMltTable_temp ) ) { 
    if ( $verbose ) { print "OK: MLT(s) exist\n";}
    &get_mlt;
} else { 
    if ( $verbose ) { print "OK: NO MLT(s)\n"; }
}

# check IS-IS interfaces for errors
# setup some counters for IS-IS interface error checking
my $isis_interfaces=0;
my $isis_interface_errors=0;
for my $key ( sort {$a<=>$b} keys %isis) {
    if ( $verbose ) { print "processing key=$key IfIndex=$isis{$key}{IfIndex} AdminState=$isis{$key}{AdminState} Operstate=$isis{$key}{OperState} NumUpAdj=$isis{$key}{NumUpAdj}\n"; }
    if (defined $isis{$key}{AdminState} && $isis{$key}{AdminState} eq "enabled" && defined $isis{$key}{OperState} && defined $isis{$key}{NumUpAdj}){
        if ($isis{$key}{OperState} ne "up"){
            $isis{$key}{error} = 1;
        } elsif ( $isis{$key}{OperState} eq "up" && $isis{$key}{NumUpAdj} ne "1" ){
            $isis{$key}{error} = 1;
        } elsif ( $isis{$key}{OperState} eq "up" && $isis{$key}{NumUpAdj} eq "1" ){
            $isis{$key}{error} = 0;
        } else {  
            print "unknown "; 
        }
    }
    if ( defined $isis{$key}{error} && $isis{$key}{error} == 1){
        $isis_interface_errors++;
        if ( $verbose ) { print "error key=$key IfIndex=$isis{$key}{IfIndex} AdminState=$isis{$key}{AdminState} Operstate=$isis{$key}{OperState} NumUpAdj=$isis{$key}{NumUpAdj}\n"; }
    }
    $isis_interfaces++;
}

&check_isis_errors;

### Print results of concatenation of strings
if (defined $statewarning) {  
     print "$rstring";
     print "$estring";
     exit $STATE_WARNING; 
} 
else { 
     print "$rstring";
     exit $STATE_OK;  
}

sub check_isis_errors {
    # check IS-IS interfaces for errors
    # setup some counters for IS-IS interface error checking
    my $isis_interfaces=0;
    my $isis_interface_errors=0;
    for my $key ( sort {$a<=>$b} keys %isis) {
        if ( $verbose ) { print "processing key=$key IfIndex=$isis{$key}{IfIndex} AdminState=$isis{$key}{AdminState} "; } 
        if ( $verbose ) { print "Operstate=$isis{$key}{OperState} NumUpAdj=$isis{$key}{NumUpAdj}\n"; }
        if (defined $isis{$key}{AdminState} && $isis{$key}{AdminState} eq "enabled" && defined $isis{$key}{OperState} && defined $isis{$key}{NumUpAdj}){
            if ($isis{$key}{OperState} ne "up"){
                $isis{$key}{error} = 1;
            } elsif ( $isis{$key}{OperState} eq "up" && $isis{$key}{NumUpAdj} ne "1" ){
                $isis{$key}{error} = 1;
            } elsif ( $isis{$key}{OperState} eq "up" && $isis{$key}{NumUpAdj} eq "1" ){
                $isis{$key}{error} = 0;
            } else {
                print "unknown ";
            }
        }
        if ( defined $isis{$key}{error} && $isis{$key}{error} == 1){
                $isis_interface_errors++;
            if ( $verbose ) { print "error key=$key IfIndex=$isis{$key}{IfIndex} AdminState=$isis{$key}{AdminState} "; }
            if ( $verbose ) { print "Operstate=$isis{$key}{OperState} NumUpAdj=$isis{$key}{NumUpAdj}\n"; }
        }
        $isis_interfaces++;
    }
    if ($isis_interface_errors == 0){
        $rstring .= "OK isis: $isis_interfaces interface(s) $isis_interface_errors errors\n";
    } else {
        $rstring .= "WARNING isis: $isis_interfaces interface(s) $isis_interface_errors error(s)<br>\n";
    }

    for my $key ( sort {$a<=>$b} keys %isis) {
        if ( defined $isis{$key}{error} && $isis{$key}{error} == 1){
            $statewarning = 1;
            # Get ifDescr, ifName, ifAlias, ifAdminStatus for IS-IS interfaces
            my $i = $isis{$key}{IfIndex};
            my $command ="$snmpget 1.3.6.1.2.1.2.2.1.2.$i";
            my $result =`$command`; if ($?) { print "Error command failed: $cmd\n"; exit $STATE_UNKNOWN; }
            $isis{$key}{ifDescr} = &fix_snmp_result($result);
            $command ="$snmpget 1.3.6.1.2.1.31.1.1.1.1.$i";
            $result =`$command`; if ($?) { print "Error command failed: $cmd\n"; exit $STATE_UNKNOWN; }
            $isis{$key}{ifName} = &fix_snmp_result($result);
            $command ="$snmpget 1.3.6.1.2.1.31.1.1.1.18.$i";
            $result =`$command`; if ($?) { print "Error command failed: $cmd\n"; exit $STATE_UNKNOWN; }
            $isis{$key}{ifAlias} = &fix_snmp_result($result);
            $command ="$snmpget 1.3.6.1.2.1.2.2.1.7.$i";
            $result =`$command`; if ($?) { print "Error command failed: $cmd\n"; exit $STATE_UNKNOWN; }
            $isis{$key}{ifAdminStatus} = &fix_snmp_result($result);
            if ( $verbose ) { print "Error: key=$key IfIndex=$isis{$key}{IfIndex} ifDescr=*$isis{$key}{ifDescr}* ifName=*$isis{$key}{ifName}* ifAlias=*$isis{$key}{ifAlias}* "; } 
            if ( $verbose ) { print "AdminState=$isis{$key}{AdminState} Operstate=$isis{$key}{OperState} NumUpAdj=$isis{$key}{NumUpAdj}\n"; }
            if (defined $isis{$key}{ifDescr} && $isis{$key}{ifDescr} ne "") { $estring .= "interface *$isis{$key}{ifDescr}* "; }
            #if (defined $isis{$key}{ifName} && $isis{$key}{ifName} ne "") { $estring .=  "*$isis{$key}{ifName}* "; }
            if (defined $isis{$key}{ifAlias} && $isis{$key}{ifAlias} ne "" ) { $estring .= "*$isis{$key}{ifAlias}* "; }
            if (defined $isis{$key}{InterfaceCircIndex} && $isis{$key}{InterfaceCircIndex} ne "" ) { $estring .= "logical-intf isis $isis{$key}{InterfaceCircIndex} "; }
            if (defined $isis{$key}{LogicalInterfaceName} && $isis{$key}{LogicalInterfaceName} ne "" ) { $estring .= "$isis{$key}{LogicalInterfaceName} "; }
            if (defined $isis{$key}{rcMltId} && $isis{$key}{rcMltId} ne "" ) { $estring .= "mlt $isis{$key}{rcMltId} "; }
            if (defined $isis{$key}{rcMltName} && $isis{$key}{rcMltName} ne "" ) { $estring .= "$isis{$key}{rcMltName} "; }
            $estring =~ s/\s+$//; #remove trailing spaces
            $estring .= "<br>\n";
        }
    }
}

sub get_isis_logical {
    if ( $verbose ) { print "rcIsisLogicalInterfaceIfIndex\n@logical_temp\n"; }
    if ( @logical_temp ) {
        foreach (@logical_temp) {
            my ($index, $result) = &chopit($_);
            $RcIsisLogicalInterfaceEntry{$index}{IfIndex} = $result;
            if ( $verbose ) { print "rcIsisLogicalInterfaceIfIndex=$RcIsisLogicalInterfaceEntry{$index}{IfIndex}\n"; }
         }
         if ( $verbose ) { print "\n"; }
     }
     @logical_temp = `$snmpwalk 1.3.6.1.4.1.2272.1.63.26.1.8`;
     if ( $verbose ) { print "rcIsisLogicalInterfaceName\n@logical_temp\n"; }
     if ( @logical_temp ) {
         foreach (@logical_temp) {
             my ($index, $result) = &chopit($_);
             $RcIsisLogicalInterfaceEntry{$index}{LogicalInterfaceName} = $result;
             if ( $verbose ) { print "rcIsisLogicalInterfaceName=$RcIsisLogicalInterfaceEntry{$index}{LogicalInterfaceName}\n"; }
          }
         if ( $verbose ) { print "\n"; }
     }
     @logical_temp = `$snmpwalk 1.3.6.1.4.1.2272.1.63.26.1.10`;
     if ( $verbose ) { print "rcIsisLogicalInterfaceCircIndex\n@logical_temp\n"; }
     if ( @logical_temp ) {
         foreach (@logical_temp) {
             my ($index, $result) = &chopit($_);
             $RcIsisLogicalInterfaceEntry{$index}{InterfaceCircIndex} = $result;
             if ( $verbose ) { print "rcIsisLogicalInterfaceCircIndex=$RcIsisLogicalInterfaceEntry{$index}{InterfaceCircIndex}\n"; }
          }
         if ( $verbose ) { print "\n"; }
     }
     for my $key ( sort {$a<=>$b} keys %RcIsisLogicalInterfaceEntry){
         if ( $verbose ) { print "RcIsisLogicalInterfaceEntry key=$key\n"; }
          for my $keyisis ( sort {$a<=>$b} keys %isis){
              if ( $RcIsisLogicalInterfaceEntry{$key}{IfIndex} eq $isis{$keyisis}{IfIndex}){
                $isis{$keyisis}{LogicalInterfaceName} = $RcIsisLogicalInterfaceEntry{$key}{LogicalInterfaceName};
                $isis{$keyisis}{InterfaceCircIndex} = $RcIsisLogicalInterfaceEntry{$key}{InterfaceCircIndex};
              }
         }
     }
}

sub get_mlt {
    if ( $verbose ) { print "rcMltId\n@rcMltTable_temp\n"; }
    if ( @rcMltTable_temp ) {
        foreach (@rcMltTable_temp) {
            my ($index, $result) = &chopit($_);
            $rcMltTable{$index}{rcMltId} = $result;
            if ( $verbose ) { print "rcMltId=$rcMltTable{$index}{rcMltId}\n"; }
         }
         if ( $verbose ) { print "\n"; }
     }
     # Get names of MLTs
     @rcMltTable_temp = `$snmpwalk 1.3.6.1.4.1.2272.1.17.10.1.2`;
     if ( $verbose ) { print "rcMltName\n@rcMltTable_temp\n"; }
     if ( @rcMltTable_temp ) {
         foreach (@rcMltTable_temp) {
            my ($index, $result) = &chopit($_);
            $rcMltTable{$index}{rcMltName} = $result;
            if ( $verbose ) { print "rcMltName=$rcMltTable{$index}{rcMltName}\n"; }
         }
         if ( $verbose ) { print "\n"; }
     }
     # Get IfIndex number of each MLT
     @rcMltTable_temp = `$snmpwalk 1.3.6.1.4.1.2272.1.17.10.1.11`;
     if ( $verbose ) { print "rcMltIfIndex\n@rcMltTable_temp\n"; }
     if ( @rcMltTable_temp ) {
         foreach (@rcMltTable_temp) {
             my ($index, $result) = &chopit($_);
             $rcMltTable{$index}{rcMltIfIndex} = $result;
             if ( $verbose ) { print "rcMltIfIndex=$rcMltTable{$index}{rcMltIfIndex}\n"; }
         }
         if ( $verbose ) { print "\n"; }
     }
     for my $key ( sort {$a<=>$b} keys %rcMltTable){
         if ( $verbose ) { print "rcMltTable key=$key\n"; }
          for my $keyisis ( sort {$a<=>$b} keys %isis){
              if ( $rcMltTable{$key}{rcMltIfIndex} eq $isis{$keyisis}{IfIndex}){
                $isis{$keyisis}{rcMltId} = $rcMltTable{$key}{rcMltId};
                $isis{$keyisis}{rcMltName} = $rcMltTable{$key}{rcMltName};
              }
         }
     }
}

sub get_isis_interfaces {
    # Get isis information for all interfaces
    my @isisCircIfIndex = `$snmpwalk 1.3.6.1.3.37.1.3.2.1.2`;
    if ( $verbose ) { print "isisCircIfIndex\n@isisCircIfIndex\n"; }
    if ( @isisCircIfIndex ) {
        foreach (@isisCircIfIndex) {
            my ($index, $result) = &chopit($_);
            $isis{$index}{IfIndex} = $result;
            if ( $verbose ) { print "IfIndex=$isis{$index}{IfIndex}\n"; }
        }
        if ( $verbose ) { print "\n"; }
    }
    my @isisCircAdminState = `$snmpwalk 1.3.6.1.3.37.1.3.2.1.3`;
    if ( $verbose ) { print "isisCircAdminState\n@isisCircAdminState\n"; }
    if ( @isisCircAdminState ) {
        foreach (@isisCircAdminState) {
        my ($index, $result) = &chopit($_);
        $isis{$index}{AdminState} = $result;
            if ($result == 0 ) { $isis{$index}{AdminState} = "unknown";}
            elsif ($result == 1 ) { $isis{$index}{AdminState} = "enabled";}
            elsif ($result == 2 ) { $isis{$index}{AdminState} = "disabled";}
                if ( $verbose ) { print "AdminState=$isis{$index}{AdminState}\n"; }
            }
        if ( $verbose ) { print "\n"; }
    }
    my @isisCircType = `$snmpwalk 1.3.6.1.3.37.1.3.2.1.5`;
    if ( $verbose ) { print "isisCircType\n@isisCircType\n"; }
    if ( @isisCircType ) {
        foreach (@isisCircType) {
            my ($index, $result) = &chopit($_);
            $isis{$index}{Type} = $result;
            if ($result == 1 ) { $isis{$index}{Type} = "bcast";}
            elsif ($result == 2 ) { $isis{$index}{Type} = "ptpt";}
            elsif ($result == 3 ) { $isis{$index}{Type} = "staticIn";}
            elsif ($result == 4 ) { $isis{$index}{Type} = "staticOut";}
            elsif ($result == 5 ) { $isis{$index}{Type} = "dA";}
            else  { $isis{$index}{Type} = "unknown";}
            if ( $verbose ) { print "Type=$isis{$index}{Type}\n"; }
       }
            if ( $verbose ) { print "\n"; }
    }
    my @rcIsisCircuitOperState = `$snmpwalk 1.3.6.1.4.1.2272.1.63.2.1.8`;
    if ( $verbose ) { print "rcIsisCircuitOperState\n@rcIsisCircuitOperState\n"; }
    if ( @rcIsisCircuitOperState ) {
       foreach (@rcIsisCircuitOperState) {
           my ($index, $result) = &chopit($_);
           $isis{$index}{OperState} = $result;
           if ($result == 0 ) { $isis{$index}{OperState} = "unknown";}
           elsif ($result == 1 ) { $isis{$index}{OperState} = "up";}
           elsif ($result == 2 ) { $isis{$index}{OperState} = "down";}
           else  { $isis{$index}{OperState} = "unknown";}
           if ( $verbose ) { print "OperState=$isis{$index}{OperState}\n"; }
       }
           if ( $verbose ) { print "\n"; }
    }
    my @rcIsisCircuitNumAdj = `$snmpwalk 1.3.6.1.4.1.2272.1.63.2.1.9`;
    if ( $verbose ) { print "rcIsisCircuitNumAdj\n@rcIsisCircuitNumAdj\n"; }
    if ( @rcIsisCircuitNumAdj ) {
       foreach (@rcIsisCircuitNumAdj) {
           my ($index, $result) = &chopit($_);
           $isis{$index}{NumAdj} = $result;
           if ( $verbose ) { print "NumAdj=$isis{$index}{NumAdj}\n"; }
       }
       if ( $verbose ) { print "\n"; }
    }
    my @rcIsisCircuitNumUpAdj  = `$snmpwalk 1.3.6.1.4.1.2272.1.63.2.1.10`;
    if ( $verbose ) { print "rcIsisCircuitNumUpAdj\n@rcIsisCircuitNumUpAdj\n"; }
    if ( @rcIsisCircuitNumUpAdj ) {
       foreach (@rcIsisCircuitNumUpAdj) {
           my ($index, $result) = &chopit($_);
           $isis{$index}{NumUpAdj} = $result;
           if ( $verbose ) { print "NumUpAdj=$isis{$index}{NumUpAdj}\n"; }
       }
       if ( $verbose ) { print "\n"; }
    }
}

### Clean up string, split on = and return just value
sub fix_snmp_result {
     chomp $_[0];
     $_[0] =~ tr/"//d;
     # if ( $verbose ) { print "beforefix *$_[0]*\n"; }
     $_[0] =~ s/\s+/ /g; #remove multiple whitespace with single space
     $_[0] =~ s/Avaya//; #make sysDescr shorter and more readable
     $_[0] =~ s/Ethernet Routing Switch/ERS/; #make sysDescr shorter and more readable
     $_[0] =~ s/Virtual Services Platform/VSP/; #make sysDescr shorter and more readable
     $_[0] =~ s/^\s+//; #remove leading spaces
     $_[0] =~ s/\s+$//; #remove trailing spaces
     my @a = split (/=/,$_[0]);
     $a[0] =~ s/^\s+//; #remove leading spaces
     $a[0] =~ s/\s+$//; #remove trailing spaces
     if (defined $a[1]){
         $a[1] =~ s/^\s+//; #remove leading spaces
         $a[1] =~ s/\s+$//; #remove trailing spaces
         if ( grep( /No Such/, $a[1] ) ) { $a[1] = "" } 
         #if ( $verbose ) { print "return *$a[1]*\n"; }
         return $a[1];
     } else {
         return "";
     }
}

sub chopit {
     chomp $_[0];
     # if ( $verbose ) { print "beforefix *$_[0]*\n"; }
     $_[0] =~ s/\s+/ /g; #remove multiple whitespace with single space
     $_[0] =~ s/Ethernet Routing Switch/ERS/; #make sysDescr shorter and more readable
     $_[0] =~ s/Virtual Services Platform/VSP/; #make sysDescr shorter and more readable
     $_[0] =~ s/^\s+//; #remove leading spaces
     $_[0] =~ s/\s+$//; #remove trailing spaces
     my @a = split (/=/,$_[0]);
     $a[0] =~ s/^\s+//; #remove leading spaces
     $a[0] =~ s/\s+$//; #remove trailing spaces
     my @t = split(/\./, $a[0]);
     $a[1] =~ s/^\s+//; #remove leading spaces
     $a[1] =~ s/\s+$//; #remove trailing spaces
     # print "$_[0] index=$t[-1] result=$a[1]\n";
     return ("$t[-1]", "$a[1]");
}
