# setup database to store Extreme Control end-system notifications
USE ilog;

CREATE TABLE `nac` (
    `datetime` datetime DEFAULT NULL,
    `host` varchar(32) DEFAULT NULL,
    `macAddress` varchar(32) DEFAULT NULL,
    `ipAddress` varchar(32) DEFAULT NULL,
    `username` varchar(100) DEFAULT NULL,
    `hostname` varchar(32) DEFAULT NULL,
    `operatingSystemName` varchar(100) DEFAULT NULL,
    `ESType` varchar(32) DEFAULT NULL,
    `state` varchar(32) DEFAULT NULL,
    `stateDescr` varchar(100) DEFAULT NULL,
    `extendedState` varchar(100) DEFAULT NULL,
    `switchIP` varchar(32) DEFAULT NULL,
    `switchLocation` varchar(100) DEFAULT NULL,
    `switchPort` varchar(100) DEFAULT NULL,
    `switchPortId` varchar(100) DEFAULT NULL,
    `authType` varchar(32) DEFAULT NULL,
    `allAuthTypes` varchar(32) DEFAULT NULL,
    `nacProfileName` varchar(100) DEFAULT NULL,
    `reason` varchar(100) DEFAULT NULL,
    `policy` varchar(100) DEFAULT NULL,
    `firstSeentime` varchar(100) DEFAULT NULL,
    `lastSeenTime` varchar(100) DEFAULT NULL,
    `nacApplianceIp` varchar(100) DEFAULT NULL,
    `nacapplianceGroupName` varchar(100) DEFAULT NULL,
    `lastScanTime` varchar(100) DEFAULT NULL,
    `lastScanResultState` varchar(100) DEFAULT NULL,
    `ssid` varchar(100) DEFAULT NULL,
    `wirelessAp` varchar(100) DEFAULT NULL,
    `ifAlias` varchar(100) DEFAULT NULL,
    `ifDescription` varchar(100) DEFAULT NULL,
    `ifName` varchar(100) DEFAULT NULL,
    `custom1` varchar(100) DEFAULT NULL,
    `custom2` varchar(100) DEFAULT NULL,
    `custom3` varchar(100) DEFAULT NULL,
    `custom4` varchar(100) DEFAULT NULL,
    `regName` varchar(100) DEFAULT NULL,
    `regEmail` varchar(100) DEFAULT NULL,
    `regPhone` varchar(100) DEFAULT NULL,
    `regData1` varchar(100) DEFAULT NULL,
    `regData2` varchar(100) DEFAULT NULL,
    `regData3` varchar(100) DEFAULT NULL,
    `regData4` varchar(100) DEFAULT NULL,
    `regData5` varchar(100) DEFAULT NULL,
    `regDeviceDescr` varchar(100) DEFAULT NULL,
    `regSponsor` varchar(100) DEFAULT NULL,
    `memberOfGroups` varchar(100) DEFAULT NULL,
    `groupDescr1` varchar(100) DEFAULT NULL,
    `groupDescr2` varchar(100) DEFAULT NULL,
    `groupDescr3` varchar(100) DEFAULT NULL,
    `seq` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (`seq`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

GRANT ALL PRIVILEGES ON ilog.* TO 'ilog'@'localhost' IDENTIFIED BY 'ilogpassword';
