# setup database to store Extreme Ignition server access logs
USE ilog;

CREATE TABLE `ignition_catId_10` (
    `Id` bigint(32) unsigned DEFAULT NULL,
    `datetime` datetime DEFAULT NULL,
    `host` varchar(32) DEFAULT NULL,
    `msgId` SMALLINT DEFAULT NULL,
    `ADDomainAsset` varchar(32) DEFAULT NULL,
    `AssignedAsset` varchar(32) DEFAULT NULL,
    `AuthServerName` varchar(32) DEFAULT NULL,
    `AuthenticationDecision` varchar(32) DEFAULT NULL,
    `AuthenticatorIpAddr` varchar(32) DEFAULT NULL,
    `AuthenticatorName` varchar(32) DEFAULT NULL,
    `AuthenticatorType` varchar(32) DEFAULT NULL,
    `AuthorizationDecision` varchar(45) DEFAULT NULL,
    `AuthorizationRuleIds` varchar(32) DEFAULT NULL,
    `CallingStationIdAttr` varchar(32) DEFAULT NULL,
    `CredentialValidationPolicy` varchar(32) DEFAULT NULL,
    `Description` varchar(32) DEFAULT NULL,
    `DeviceMAC` varchar(32) DEFAULT NULL,
    `DeviceOSType` varchar(32) DEFAULT NULL,
    `DeviceOSVersion` varchar(32) DEFAULT NULL,
    `DeviceSubtype` varchar(32) DEFAULT NULL,
    `DeviceType` varchar(32) DEFAULT NULL,    
    `DirectoryServiceName` varchar(32) DEFAULT NULL,
    `EmbeddedAsset` varchar(32) DEFAULT NULL,
    `InnerIdentity` varchar(32) DEFAULT NULL,
    `LastAuthException` varchar(32) DEFAULT NULL,
    `LicenseGID` varchar(32) DEFAULT NULL,
    `LicenseOID` varchar(32) DEFAULT NULL,
    `NASIPAddrAttr` varchar(32) DEFAULT NULL,
    `NASPortAttr` varchar(32) DEFAULT NULL,
    `PostureProfileName` varchar(32) DEFAULT NULL,
    `PostureResult` varchar(32) DEFAULT NULL,
    `ProvisioningValues` varchar(32) DEFAULT NULL,
    `ResultCode` varchar(32) DEFAULT NULL,
    `ServiceCatName` varchar(32) DEFAULT NULL,
    `SubauthenticatorName` varchar(32) DEFAULT NULL,
    `TunnelProtocol` varchar(32) DEFAULT NULL,
    `UserNameAttr` varchar(100) DEFAULT NULL,
    `UserId` varchar(100) DEFAULT NULL,
    `seq` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (`seq`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

GRANT ALL PRIVILEGES ON ilog.* TO 'ilog'@'localhost' IDENTIFIED BY 'ilogpassword';
